---
# DHCP RELAY SERVER AKA BENCH
dhcp_relay_server: "10.0.254.254"

# MAINT TASK OPTIONS
rm-cl-support: "no"

# CUMULUS IMAGES
cmls_image_intel: "CumulusLinux-3.0.0-amd64.bin"
cmls_image_ppc: "CumulusLinux-3.0.0-powerpc.bin"

#ONIE IMAGE LOCATION
onie_installer_intel: "/var/www/CumulusLinux-3.0.0-amd64.bin"
onie_installer_ppc: "/var/www/CumulusLinux-3.0.0-powerpc.bin"
web_root: "/var/www/"

# REPO URLS
sj1_repo_url: "http://sj1-repo.bjn.io/"
eu1_repo_url: "http://eu1-repo.bjn.io/"
au1_repo_url: "http://au1-repo.bjn.io/"
sg1_repo_url: "http://sg1-repo.bjn.io/"
bitcouncil_apt_repo_url: "http://10.100.0.15/bc-apt/debs"

#DEB REPOS
apt_cache_timeout: 900
cmls_main_repo: "deb http://repo.cumulusnetworks.com CumulusLinux-3.0 main addons updates"
cmls_security_repo: "deb http://repo.cumulusnetworks.com CumulusLinux-3.0 security-updates"
cmls_testing_repo: "deb http://repo.cumulusnetworks.com CumulusLinux-3.0 testing"
debian_main_repo: "deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free"
debian_src_repo: "deb-src http://ftp.us.debian.org/debian/ wheezy main contrib non-free"
bitcouncil_apt_repo: "deb http://10.0.254.254/bc-apt/debs"

# USER ACCOUNTS
user_root: root
user_admin: admin

# APACHE
apache_fqdn: localhost

# NTP
ntp_server_1: 10.0.254.254
ntp_server_2: 10.0.254.254

# DNS Name Servers
dns_domain: bluejeansnet.com
dns_search_domain: bluejeansnet.com
dns_int_ns1: 8.8.8.8
dns_int_ns2: 8.8.4.4
dns_ext_ns1: 8.8.8.8
dns_ext_ns2: 8.8.4.4

# QUAGGA PASSWORDS
zebra_passwd: password!
quagga_passwd: password!

rabbit_server: 'bc-z-rabbitmq-internal-elb.bjn.io'
sensu_client_log_level: 'warn'

### Custom Ansible Managed Header
ansible_managed_bjn: "This file is managed by Ansible.%n template: '{{ file }}' %n date: %Y-%m-%d %H:%M:%S"