---
  - name: create ssh keys for cumulus root and admin users
    user: name={{ item }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    with_items:
      - root
      - cumulus
      - admin

  - name: copy public key to /var/www/authorized_keys
    copy: src=/root/.ssh/id_rsa.pub dest=/var/www/authorized_keys