---
  - name: restart sensu_client
    service: name=sensu-client state=restarted

  - name: restart networking
    service: name=networking state=restarted

  - name: restart dnsmasq
    service: name=dnsmasq state=restarted

  - name: restart isc-dhcp-server
    service: name=isc-dhcp-server state=restarted

  - name: restart apache2
    service: name=apache2 state=restarted